/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.application.vevhar;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import org.application.Application;
import org.application.dashboard.Dashboard;
import org.application.plot.EntityPlot;
import org.application.plot.PlotDAO;

/**
 *
 * @author abhayjadhav
 */
public class VevharUI extends javax.swing.JPanel {

    public static VevharUI instance = null;
    public VevharDAO vevharDAO = null;
    private EntityAushadh aushadh = null;
    private EntityJama jama = null;
    private EntityKamgar kamgar = null;
    private  EntityKharch kharch = null;
    private EntityKhat khat = null;
    private EntityPani pani = null;
    /**
     * Creates new form PlotSelection
     */
    public VevharUI() {
        initComponents();
        build_GUI();
    }
    
    public static VevharUI getInstance() {
        if (instance == null) {
            instance = new VevharUI();
        }
        return instance;
    }
    
    public static void disposeInstance() {
        instance = null;
    }
    
    private void build_GUI() {
        this.setBorder(BorderFactory.createTitledBorder(""));
        this.setPreferredSize(new Dimension(750, 600));
//        try {
            getAllPloat();
            dinakText.setDate(new Date());
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(VevharUI.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(VevharUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
    
    public void getAllPloat() {
        PlotDAO plotDAO = new PlotDAO();
        ArrayList<EntityPlot> plotList = plotDAO.getAllPlot();//new ArrayList<>();
        plotNoCombo.removeAllItems();
        if(plotList !=null) {
            for(EntityPlot plot : plotList) {
                plotNoCombo.addItem(plot.getPlotNo());
            }
        }
        
//        Class.forName("com.mysql.jdbc.Driver");
//        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/testing","root","");
//        //Search
//        Statement stm = con.createStatement();
//        String query = "select * from ploat";
//        ResultSet rs = stm.executeQuery(query);
//        ArrayList<Integer> ploatList = new ArrayList<>();
//        while(rs.next()) {
//            ploatList.add(rs.getInt("ploatNo"));
//        }
//        
//        ploatNoCombo.removeAllItems();
//        
//        if(ploatList != null) {
//            for(Integer plotNo : ploatList) {
//                ploatNoCombo.addItem(plotNo);
//            }
//        }
//        stm.close();
//        con.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fillerLeft = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        fillerUp = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25));
        fillerRight = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        fillerDown = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        divasText = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        aushadhNavText = new javax.swing.JTextField();
        aushadhPrmanText = new javax.swing.JTextField();
        aushadhRogacheNavText = new javax.swing.JTextField();
        aushadhPrinamText = new javax.swing.JTextField();
        aushadhVatavrnCombo = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        khatNavText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        khatPrmanText = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        khatPaniText = new javax.swing.JTextField();
        khatPrinamText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        paniTaasText = new javax.swing.JTextField();
        paniPrkarCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        kamgarPrkarText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kamgarSankhyaText = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        kharchPrkarText = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        kharchUpPrkarText = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        kharchRakkamText = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jamaPrkarText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jamaUpPrkarText = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jamaRakkamText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        dinakText = new com.toedter.calendar.JDateChooser();
        vatavrnCombo = new javax.swing.JComboBox();
        plotNoCombo = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());
        add(fillerLeft, java.awt.BorderLayout.LINE_START);
        add(fillerUp, java.awt.BorderLayout.PAGE_START);
        add(fillerRight, java.awt.BorderLayout.LINE_END);
        add(fillerDown, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("दैनंदिन व्यवहार"));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("वातावरण");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 120, 140, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("दिनांक");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 160, 120, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("दिवस");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 80, 140, 30);
        jPanel1.add(divasText);
        divasText.setBounds(220, 70, 200, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("औषधाचे नाव");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 30, 150, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("औषधाचे प्रमाण");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 70, 150, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("वातावरण");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 110, 150, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("रोगाचे नाव");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 150, 120, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("परिणाम");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 190, 120, 30);
        jPanel2.add(aushadhNavText);
        aushadhNavText.setBounds(190, 20, 300, 40);
        jPanel2.add(aushadhPrmanText);
        aushadhPrmanText.setBounds(190, 60, 300, 40);
        jPanel2.add(aushadhRogacheNavText);
        aushadhRogacheNavText.setBounds(190, 140, 300, 40);
        jPanel2.add(aushadhPrinamText);
        aushadhPrinamText.setBounds(190, 180, 300, 40);

        aushadhVatavrnCombo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        aushadhVatavrnCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "कोरडे", "ढगाळ", "पावसाळी" }));
        jPanel2.add(aushadhVatavrnCombo);
        aushadhVatavrnCombo.setBounds(190, 100, 300, 40);

        jTabbedPane1.addTab("औषध फवारणी", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel21.setText("खत नाव");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(30, 30, 150, 30);
        jPanel6.add(khatNavText);
        khatNavText.setBounds(190, 20, 300, 40);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel22.setText("खत प्रमाण");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(30, 70, 150, 30);
        jPanel6.add(khatPrmanText);
        khatPrmanText.setBounds(190, 60, 300, 40);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel23.setText("पाणी");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(30, 110, 120, 30);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel24.setText("परिणाम");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(30, 150, 120, 30);
        jPanel6.add(khatPaniText);
        khatPaniText.setBounds(190, 100, 300, 40);
        jPanel6.add(khatPrinamText);
        khatPrinamText.setBounds(190, 140, 300, 40);

        jTabbedPane1.addTab("खत व्यवस्थापन", jPanel6);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel13.setText("प्रकार");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(30, 30, 150, 30);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel15.setText("किती तास सोडले");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(30, 80, 150, 30);
        jPanel4.add(paniTaasText);
        paniTaasText.setBounds(190, 70, 200, 40);

        paniPrkarCombo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        paniPrkarCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "विहिरीचे पाणी", "बोरचे पाणी", "टँकर पाणी" }));
        jPanel4.add(paniPrkarCombo);
        paniPrkarCombo.setBounds(190, 30, 200, 40);

        jTabbedPane1.addTab("पाणी व्यवस्थापन", jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel9.setText("कामाचा प्रकार");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 30, 150, 30);
        jPanel3.add(kamgarPrkarText);
        kamgarPrkarText.setBounds(190, 20, 300, 40);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel10.setText("कामगार संख्या");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(30, 70, 150, 30);
        jPanel3.add(kamgarSankhyaText);
        kamgarSankhyaText.setBounds(190, 60, 300, 40);

        jTabbedPane1.addTab("कामगार", jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel25.setText("खर्चाचा प्रकार");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(30, 30, 150, 30);
        jPanel7.add(kharchPrkarText);
        kharchPrkarText.setBounds(190, 20, 300, 40);

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel26.setText("उपप्रकार");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(30, 70, 150, 30);
        jPanel7.add(kharchUpPrkarText);
        kharchUpPrkarText.setBounds(190, 60, 300, 40);

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel29.setText("खर्चाची रक्कम");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(30, 110, 150, 30);
        jPanel7.add(kharchRakkamText);
        kharchRakkamText.setBounds(190, 100, 300, 40);

        jTabbedPane1.addTab("खर्च", jPanel7);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel17.setText("जमेचा प्रकार");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(30, 30, 150, 30);
        jPanel5.add(jamaPrkarText);
        jamaPrkarText.setBounds(190, 20, 300, 40);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel18.setText("उपप्रकार");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(30, 70, 150, 30);
        jPanel5.add(jamaUpPrkarText);
        jamaUpPrkarText.setBounds(190, 60, 300, 40);

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel30.setText("जमेची रक्कम");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(30, 110, 150, 30);
        jPanel5.add(jamaRakkamText);
        jamaRakkamText.setBounds(190, 100, 300, 40);

        jTabbedPane1.addTab("जमा", jPanel5);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 200, 630, 280);

        cancelButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        cancelButton.setText("रद्द करा");
        cancelButton.setSize(new java.awt.Dimension(150, 40));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);
        cancelButton.setBounds(340, 490, 150, 40);

        saveButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        saveButton.setText("जतन करा");
        saveButton.setSize(new java.awt.Dimension(150, 40));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton);
        saveButton.setBounds(140, 490, 150, 40);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel11.setText("प्लॉट नंबर");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 40, 150, 30);

        dinakText.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(dinakText);
        dinakText.setBounds(220, 150, 200, 40);

        vatavrnCombo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        vatavrnCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "कोरडे", "ढगाळ", "पावसाळी" }));
        vatavrnCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vatavrnComboItemStateChanged(evt);
            }
        });
        jPanel1.add(vatavrnCombo);
        vatavrnCombo.setBounds(220, 110, 200, 40);

        plotNoCombo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jPanel1.add(plotNoCombo);
        plotNoCombo.setBounds(220, 30, 200, 40);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        Application.getInstance().display_Panel(Dashboard.getInstance());
        disposeInstance();
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        vevharDAO = new VevharDAO();
        int ploatNo = Integer.parseInt(plotNoCombo.getSelectedItem().toString());
        int divas = Integer.parseInt(divasText.getText());
        String vatavrn = vatavrnCombo.getSelectedItem().toString();
        java.util.Date date= dinakText.getDate();
        java.sql.Date dinak=new java.sql.Date(date.getTime());
        if(checkAushadhEmpty()) {
            aushadh = new EntityAushadh();
            
            aushadh.setPlotNo(ploatNo);
            aushadh.setDivas(divas);
            aushadh.setVatavrn(vatavrn);
            aushadh.setDinak(dinak);
            
            aushadh.setAushadhNav(aushadhNavText.getText());
            aushadh.setAushadhPrman(aushadhPrmanText.getText());
            aushadh.setAushadhVatavrn(aushadhVatavrnCombo.getSelectedItem().toString());
            aushadh.setAushadhRogacheNav(aushadhRogacheNavText.getText());
            aushadh.setAushadhPrinam(aushadhPrinamText.getText());
            if(vevharDAO.saveAushad(aushadh)) {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Aushad Saved succesfully!",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Failed to Save Aushad!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        if(checkKhatEmpty()) {
            khat = new EntityKhat();
            
            khat.setPlotNo(ploatNo);
            khat.setDivas(divas);
            khat.setVatavrn(vatavrn);
            khat.setDinak(dinak);
            
            khat.setKhatNav(khatNavText.getText());
            khat.setKhatPrman(khatPrmanText.getText());
            khat.setKhatPani(khatPaniText.getText());
            khat.setKhatPrinam(khatPrinamText.getText());
            if(vevharDAO.saveKhat(khat)) {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Khat Saved succesfully!",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Failed to Save Khat!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(checkPaniEmpty()) {
            pani = new EntityPani();
            
            pani.setPlotNo(ploatNo);
            pani.setDivas(divas);
            pani.setVatavrn(vatavrn);
            pani.setDinak(dinak);
            
            pani.setpaniPrkar(paniPrkarCombo.getSelectedItem().toString());
            pani.setpaniTaas(paniTaasText.getText());
            if(vevharDAO.savePani(pani)) {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Pani Saved succesfully!",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Failed to Save Pani!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(checkKamgarEmpty()) {
            kamgar = new EntityKamgar();
            
            kamgar.setPlotNo(ploatNo);
            kamgar.setDivas(divas);
            kamgar.setVatavrn(vatavrn);
            kamgar.setDinak(dinak);
            
            kamgar.setKamgarPrkar(kamgarPrkarText.getText());
            kamgar.setKamgarSankhya(Integer.parseInt(kamgarSankhyaText.getText()));
            if(vevharDAO.saveKamgar(kamgar)) {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Kamgar Saved succesfully!",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Failed to Save Kamgar!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(checkKharchEmpty()) {
            kharch = new EntityKharch();
            
            kharch.setPlotNo(ploatNo);
            kharch.setDivas(divas);
            kharch.setVatavrn(vatavrn);
            kharch.setDinak(dinak);
            
            kharch.setKharchPrkar(kharchPrkarText.getText());
            kharch.setKharchUpPrkar(kharchUpPrkarText.getText());
            kharch.setKharchRakkam(Integer.parseInt(kharchRakkamText.getText()));
            if(vevharDAO.saveKharch(kharch)) {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Kharch Saved succesfully!",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Failed to Save Kharch!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(checkJamaEmpty()) {
            jama = new EntityJama();
            
            jama.setPlotNo(ploatNo);
            jama.setDivas(divas);
            jama.setVatavrn(vatavrn);
            jama.setDinak(dinak);
            
            jama.setJamaPrkar(jamaPrkarText.getText());
            jama.setJamaUpPrkar(jamaUpPrkarText.getText());
            jama.setJamaRakkam(Integer.parseInt(jamaRakkamText.getText()));
            if(vevharDAO.saveJama(jama)) {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Jama Saved succesfully!",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Failed to Save Jama!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
//        System.out.println("DATE : "+dinakText.getDate());
        
//        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/testing","root","");
//            //aushadh
//            String query = "insert into aushadhVevhar(ploatNo,divas,vatavrn,dinak,aushadhNav,aushadhPrman,aushadhVatavrn,aushadhRogacheNav,aushadhPrinam) values(?,?,?,?,?,?,?,?,?)";
//            
//            PreparedStatement preparedStmt = con.prepareStatement(query);
//            preparedStmt.setInt(1, ploatNo);
//            preparedStmt.setInt (2, days);
//            preparedStmt.setString (3, climate);
//            preparedStmt.setDate(4, sqlDate);
//            preparedStmt.setString (5, aushadhNavText.getText());
//            preparedStmt.setString (6, aushadhPrmanText.getText());
//            preparedStmt.setString (7, aushadhVatavrnCombo.getSelectedItem().toString());
//            preparedStmt.setString (8, aushadhRogacheNavText.getText());
//            preparedStmt.setString (9, aushadhPrinamText.getText());
//            preparedStmt.execute();
//            
//            
//            //Khat
//            query = "insert into khatVevhar(ploatNo,days,climate,dinak,khatNav,khatPrman,khatPani,khatPrinam) values(?,?,?,?,?,?,?,?)";
//            
//            preparedStmt = con.prepareStatement(query);
//            preparedStmt.setInt(1, ploatNo);
//            preparedStmt.setInt (2, days);
//            preparedStmt.setString (3, climate);
//            preparedStmt.setDate(4, sqlDate);
//            preparedStmt.setString (5, khatNavText.getText());
//            preparedStmt.setString (6, khatPrmanText.getText());
//            preparedStmt.setString (7, khatPaniText.getText());
//            preparedStmt.setString (8, khatPrinamText.getText());
//            preparedStmt.execute();
//            
//            //pani
//            query = "insert into paniVevhar(ploatNo,days,climate,dinak,paniPrkar,paniTaas) values(?,?,?,?,?,?)";
//            
//            preparedStmt = con.prepareStatement(query);
//            preparedStmt.setInt(1, ploatNo);
//            preparedStmt.setInt (2, days);
//            preparedStmt.setString (3, climate);
//            preparedStmt.setDate(4, sqlDate);
//            preparedStmt.setString (5, paniPrkarCombo.getSelectedItem().toString());
//            preparedStmt.setString (6, paniTaasText.getText());
//            preparedStmt.execute();
//            
//            //kamgar
//            query = "insert into kamgarVevhar(ploatNo,days,climate,dinak,kamgarPrkar,kamgarSankhya) values(?,?,?,?,?,?)";
//            
//            preparedStmt = con.prepareStatement(query);
//            preparedStmt.setInt(1, ploatNo);
//            preparedStmt.setInt (2, days);
//            preparedStmt.setString (3, climate);
//            preparedStmt.setDate(4, sqlDate);
//            preparedStmt.setString (5, kamgarPrkarText.getText());
//            preparedStmt.setString (6, kamgarSankhyaText.getText());
//            preparedStmt.execute();
//            
//            //kharch
//            query = "insert into kharchVevhar(ploatNo,days,climate,dinak,kharchPrkar,kharchUpPrkar,kharchRakkam) values(?,?,?,?,?,?,?)";
//            
//            preparedStmt = con.prepareStatement(query);
//            preparedStmt.setInt(1, ploatNo);
//            preparedStmt.setInt (2, days);
//            preparedStmt.setString (3, climate);
//            preparedStmt.setDate(4, sqlDate);
//            preparedStmt.setString (5, kharchPrkarText.getText());
//            preparedStmt.setString (6, kharchUpPrkarText.getText());
//            preparedStmt.setString (7, kharchRakkamText.getText());
//            preparedStmt.execute();
//            
//            //jama
//            query = "insert into jamaVevhar(ploatNo,days,climate,dinak,jamaPrkar,jamaUpPrkar,jamaRakkam) values(?,?,?,?,?,?,?)";
//            
//            preparedStmt = con.prepareStatement(query);
//            preparedStmt.setInt(1, ploatNo);
//            preparedStmt.setInt (2, days);
//            preparedStmt.setString (3, climate);
//            preparedStmt.setDate(4, sqlDate);
//            preparedStmt.setString (5, jamaPrkarText.getText());
//            preparedStmt.setString (6, jamaUpPrkarText.getText());
//            preparedStmt.setString (7, jamaRakkamText.getText());
//            preparedStmt.execute();
//            
//            con.close();
//        } catch (Exception ex) {
//            Logger.getLogger(VevharUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
            
            
            
        
            
        clearText();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void vatavrnComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vatavrnComboItemStateChanged
        // TODO add your handling code here:
        aushadhVatavrnCombo.setSelectedItem(vatavrnCombo.getSelectedItem());
    }//GEN-LAST:event_vatavrnComboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aushadhNavText;
    private javax.swing.JTextField aushadhPrinamText;
    private javax.swing.JTextField aushadhPrmanText;
    private javax.swing.JTextField aushadhRogacheNavText;
    private javax.swing.JComboBox aushadhVatavrnCombo;
    private javax.swing.JButton cancelButton;
    private com.toedter.calendar.JDateChooser dinakText;
    private javax.swing.JTextField divasText;
    private javax.swing.Box.Filler fillerDown;
    private javax.swing.Box.Filler fillerLeft;
    private javax.swing.Box.Filler fillerRight;
    private javax.swing.Box.Filler fillerUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jamaPrkarText;
    private javax.swing.JTextField jamaRakkamText;
    private javax.swing.JTextField jamaUpPrkarText;
    private javax.swing.JTextField kamgarPrkarText;
    private javax.swing.JTextField kamgarSankhyaText;
    private javax.swing.JTextField kharchPrkarText;
    private javax.swing.JTextField kharchRakkamText;
    private javax.swing.JTextField kharchUpPrkarText;
    private javax.swing.JTextField khatNavText;
    private javax.swing.JTextField khatPaniText;
    private javax.swing.JTextField khatPrinamText;
    private javax.swing.JTextField khatPrmanText;
    private javax.swing.JComboBox paniPrkarCombo;
    private javax.swing.JTextField paniTaasText;
    private javax.swing.JComboBox plotNoCombo;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox vatavrnCombo;
    // End of variables declaration//GEN-END:variables

    private boolean checkAushadhEmpty() {
        String message = "";
        
        if (divasText.getText().equals("")) {
            message = "दिवस लिहा";
        } else if (aushadhNavText.getText().equals("")) {
            message = "औषधाचे नाव लिहा";
        } else if (aushadhPrmanText.getText().equals("")) {
            message = "औषधाचे प्रमाण लिहा";
        } else if (aushadhRogacheNavText.getText().equals("")) {
            message = "रोगाचे नाव लिहा";
        } else if (aushadhPrinamText.getText().equals("")) {
            message = "परिणाम लिहा";
        } else {
            return true;
        }
        JOptionPane.showMessageDialog(Application.getCurrentPanel(), message, "Error", JOptionPane.ERROR_MESSAGE);
        return false;
        
    }
    
    private boolean checkKhatEmpty() {
        String message = "";
        
        if (divasText.getText().equals("")) {
            message = "दिवस लिहा";
        } else if (khatNavText.getText().equals("")) {
            message = "खत नाव लिहा";
        } else if (khatPrmanText.getText().equals("")) {
            message = "खत प्रमाण लिहा";
        } else if (khatPaniText.getText().equals("")) {
            message = "पाणी लिहा";
        } else if (khatPrinamText.getText().equals("")) {
            message = "परिणाम लिहा";
        } else {
            return true;
        }
        JOptionPane.showMessageDialog(Application.getCurrentPanel(), message, "Error", JOptionPane.ERROR_MESSAGE);
        return false;
        
    }
    
    private boolean checkPaniEmpty() {
        String message = "";
        
        if (divasText.getText().equals("")) {
            message = "दिवस लिहा";
        } else if (paniTaasText.getText().equals("")) {
            message = "किती तास सोडले लिहा";
        } else {
            return true;
        }
        JOptionPane.showMessageDialog(Application.getCurrentPanel(), message, "Error", JOptionPane.ERROR_MESSAGE);
        return false;
        
    }
    
    private boolean checkKamgarEmpty() {
        String message = "";
        
        if (divasText.getText().equals("")) {
            message = "दिवस लिहा";
        } else if (kamgarPrkarText.getText().equals("")) {
            message = "कामाचा प्रकार लिहा";
        } else if (kamgarSankhyaText.getText().equals("")) {
            message = "कामगार संख्या लिहा";
        } else {
            return true;
        }
        JOptionPane.showMessageDialog(Application.getCurrentPanel(), message, "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    private boolean checkKharchEmpty() {
        String message = "";
        
        if (divasText.getText().equals("")) {
            message = "दिवस लिहा";
        } else if (kharchPrkarText.getText().equals("")) {
            message = "खर्चाचा प्रकार लिहा";
        } else if (kharchUpPrkarText.getText().equals("")) {
            message = "खर्चाचा उपप्रकार लिहा";
        } else if (kharchRakkamText.getText().equals("")) {
            message = "खर्चाची रक्कम लिहा";
        } else {
            return true;
        }
        JOptionPane.showMessageDialog(Application.getCurrentPanel(), message, "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    private boolean checkJamaEmpty() {
        String message = "";
        
        if (divasText.getText().equals("")) {
            message = "दिवस लिहा";
        } else if (jamaPrkarText.getText().equals("")) {
            message = "जमेचा प्रकार लिहा";
        } else if (jamaUpPrkarText.getText().equals("")) {
            message = "जमेचा उपप्रकार लिहा";
        } else if (jamaRakkamText.getText().equals("")) {
            message = "जमेची रक्कम लिहा";
        } else {
            return true;
        }
        JOptionPane.showMessageDialog(Application.getCurrentPanel(), message, "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    private void clearText() {
        
        divasText.setText("");
        aushadhNavText.setText("");
        aushadhPrmanText.setText("");
        aushadhRogacheNavText.setText("");
        aushadhPrinamText.setText("");
        khatNavText.setText("");
        khatPrmanText.setText("");
        khatPaniText.setText("");
        khatPrinamText.setText("");
        paniTaasText.setText("");
        kamgarPrkarText.setText("");
        kamgarSankhyaText.setText("");
        kharchPrkarText.setText("");
        kharchUpPrkarText.setText("");
        kharchRakkamText.setText("");
        jamaPrkarText.setText("");
        jamaUpPrkarText.setText("");
        jamaRakkamText.setText("");
        
    }
    
}
