/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.application.plot;

import java.awt.Dimension;
import javax.swing.BorderFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.application.Application;
import org.application.dashboard.Dashboard;

/**
 *
 * @author abhayjadhav
 */
public class PlotCreateUI extends javax.swing.JPanel {

    public static PlotCreateUI instance = null;
    private EntityPlot plot = null;
    public PlotDAO plotDAO = null;
    
    ///connection
    private Connection connect = null;
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null;
    /**
     * Creates new form PlotInfo
     */
    public static PlotCreateUI getInstance() {
        if (instance == null) {
            instance = new PlotCreateUI();
        }
        return instance;
    }
    
    public static void disposeInstance() {
        instance = null;
    }
    
    public PlotCreateUI() {
        initComponents();
        build_GUI();
    }
    
    public void build_GUI() {
        
        this.setBorder(BorderFactory.createTitledBorder(""));
        this.setPreferredSize(new Dimension(750, 500));
        getNextPlotID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        plotNoText = new javax.swing.JTextField();
        shetrphalText = new javax.swing.JTextField();
        zadanchiSankhyaText = new javax.swing.JTextField();
        zadanMadhilAntarText = new javax.swing.JTextField();
        olinMadhilAntarText = new javax.swing.JTextField();
        zadanchiJatText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fillerLeft = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        fillerUp = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25));
        fillerRight = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        fillerDown = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25));

        setToolTipText("");
        setAutoscrolls(true);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "प्लॉट माहिती", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        buttonSave.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        buttonSave.setText("जतन करा");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSave);
        buttonSave.setBounds(140, 380, 160, 38);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("प्लॉट नंबर");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 70, 150, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("क्षेत्रफळ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 120, 140, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("झाडांची संख्या");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 170, 160, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("झाडांमधील अंतर");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 220, 160, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("ओळींमध्ये अंतर");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 270, 150, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("झाडांची जात");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 320, 150, 30);
        jPanel1.add(plotNoText);
        plotNoText.setBounds(340, 60, 200, 40);
        jPanel1.add(shetrphalText);
        shetrphalText.setBounds(340, 110, 200, 40);
        jPanel1.add(zadanchiSankhyaText);
        zadanchiSankhyaText.setBounds(340, 160, 200, 40);
        jPanel1.add(zadanMadhilAntarText);
        zadanMadhilAntarText.setBounds(340, 210, 200, 40);
        jPanel1.add(olinMadhilAntarText);
        olinMadhilAntarText.setBounds(340, 260, 200, 40);
        jPanel1.add(zadanchiJatText);
        zadanchiJatText.setBounds(340, 310, 200, 40);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setText("रद्द करा");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 380, 150, 38);

        add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        add(fillerLeft, java.awt.BorderLayout.LINE_START);
        add(fillerUp, java.awt.BorderLayout.PAGE_START);
        add(fillerRight, java.awt.BorderLayout.LINE_END);
        add(fillerDown, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Application.getInstance().display_Panel(Dashboard.getInstance());
        disposeInstance();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        plot = new EntityPlot();
        plot.setPlotNo(Integer.parseInt(plotNoText.getText()));
        plot.setShetrphal(shetrphalText.getText());
        plot.setZadanchiSankhya(Integer.parseInt(zadanchiSankhyaText.getText()));
        plot.setZadanMadhilAntar(Integer.parseInt(zadanMadhilAntarText.getText()));
        plot.setOlinMadhilAntar(Integer.parseInt(olinMadhilAntarText.getText()));
        plot.setZadanchiJat(zadanchiJatText.getText());
        if (checkEmpty()) {
            if (plotDAO.savePlot(plot)) {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Plot Saved succesfully!",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                clearText();
                getNextPlotID();
            } else {
                JOptionPane.showMessageDialog(Application.getCurrentPanel(), "Failed to Save Plot!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_buttonSaveActionPerformed

    private boolean checkEmpty() {
        String message = "";
        
        if (shetrphalText.getText().equals("")) {
            message = "क्षेत्रफल लिहा";
        } else if (zadanchiSankhyaText.getText().equals("")) {
            message = "झाडांची संख्या लिहा";
        } else if (zadanMadhilAntarText.getText().equals("")) {
            message = "झाडांमधील अंतर लिहा";
        } else if (olinMadhilAntarText.getText().equals("")) {
            message = "ओळींमध्ये अंतर लिहा";
        } else if (zadanchiJatText.getText().equals("")) {
            message = "झाडांची जात लिहा";
        } else {
            return true;
        }
        JOptionPane.showMessageDialog(Application.getCurrentPanel(), message, "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave;
    private javax.swing.Box.Filler fillerDown;
    private javax.swing.Box.Filler fillerLeft;
    private javax.swing.Box.Filler fillerRight;
    private javax.swing.Box.Filler fillerUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField olinMadhilAntarText;
    private javax.swing.JTextField plotNoText;
    private javax.swing.JTextField shetrphalText;
    private javax.swing.JTextField zadanMadhilAntarText;
    private javax.swing.JTextField zadanchiJatText;
    private javax.swing.JTextField zadanchiSankhyaText;
    // End of variables declaration//GEN-END:variables

    private void clearText() {
        shetrphalText.setText("");
        zadanchiSankhyaText.setText("");
        zadanMadhilAntarText.setText("");
        olinMadhilAntarText.setText("");
        zadanchiJatText.setText("");
    }

    private void getNextPlotID() {
        plotDAO = new PlotDAO();
       int id = plotDAO.getNextPlotNo();
       plotNoText.setText(String.valueOf(id));
    }

}
