/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.application.plot;

import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import org.application.plot.*;

/**
 *
 * @author abhayjadhav
 */
public class PlotSelectionTest extends javax.swing.JPanel {

    public static PlotSelectionTest instance = null;
    /**
     * Creates new form PlotSelection
     */
    public PlotSelectionTest() {
        initComponents();
        build_GUI();
    }
    
    public static PlotSelectionTest getInstance() {
        if (instance == null) {
            instance = new PlotSelectionTest();
        }
        return instance;
    }
    
    private void build_GUI() {
        this.setBorder(BorderFactory.createTitledBorder(""));
        this.setPreferredSize(new Dimension(1050, 600));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fillerLeft = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        fillerUp = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25));
        fillerRight = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        fillerDown = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25));
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();

        setAutoscrolls(true);
        setLayout(new java.awt.BorderLayout());
        add(fillerLeft, java.awt.BorderLayout.LINE_START);
        add(fillerUp, java.awt.BorderLayout.PAGE_START);
        add(fillerRight, java.awt.BorderLayout.LINE_END);
        add(fillerDown, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("दैनंदिन व्यवहार"));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("वातावरण");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 120, 140, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("दिनांक");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 160, 120, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("दिवस");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 80, 140, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(220, 70, 200, 40);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setText("रद्द करा");
        jButton1.setSize(new java.awt.Dimension(150, 40));
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 760, 150, 40);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton2.setText("जतन करा");
        jButton2.setSize(new java.awt.Dimension(150, 40));
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 760, 150, 40);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel11.setText("प्लॉट नंबर");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 40, 150, 30);

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(220, 150, 200, 40);

        jComboBox2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "कोरडे", "ढगाळ", "पावसाळी" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(220, 110, 200, 40);

        jComboBox4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(220, 30, 200, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("औषध फवारणी"));
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("औषधाचे नाव");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 30, 150, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("औषधाचे प्रमाण");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 70, 150, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("वातावरण");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 110, 150, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("रोगाचे नाव");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 150, 120, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("परिणाम");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 190, 120, 30);

        jTextField4.setSize(new java.awt.Dimension(250, 40));
        jPanel2.add(jTextField4);
        jTextField4.setBounds(190, 20, 250, 40);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(190, 60, 250, 40);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(190, 140, 250, 40);
        jPanel2.add(jTextField8);
        jTextField8.setBounds(190, 180, 250, 40);

        jComboBox5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "कोरडे", "ढगाळ", "पावसाळी" }));
        jPanel2.add(jComboBox5);
        jComboBox5.setBounds(190, 100, 250, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 220, 470, 240);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("जमा"));
        jPanel5.setAutoscrolls(true);
        jPanel5.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel17.setText("जमेचा प्रकार");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(30, 30, 150, 30);

        jTextField13.setSize(new java.awt.Dimension(250, 40));
        jPanel5.add(jTextField13);
        jTextField13.setBounds(190, 20, 250, 40);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel18.setText("उपप्रकार");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(30, 70, 150, 30);

        jTextField17.setSize(new java.awt.Dimension(250, 40));
        jPanel5.add(jTextField17);
        jTextField17.setBounds(190, 60, 250, 40);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel19.setText("पाणी");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(30, 150, 120, 30);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel20.setText("परिणाम");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(30, 190, 120, 30);

        jTextField18.setSize(new java.awt.Dimension(250, 40));
        jPanel5.add(jTextField18);
        jTextField18.setBounds(190, 140, 250, 40);

        jTextField19.setSize(new java.awt.Dimension(250, 40));
        jPanel5.add(jTextField19);
        jTextField19.setBounds(190, 180, 250, 40);

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel30.setText("जमेची रक्कम");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(30, 110, 150, 30);

        jTextField27.setSize(new java.awt.Dimension(250, 40));
        jPanel5.add(jTextField27);
        jTextField27.setBounds(190, 100, 250, 40);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(500, 460, 460, 234);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("खर्च"));
        jPanel7.setAutoscrolls(true);
        jPanel7.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel25.setText("खर्चाचा प्रकार");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(30, 30, 150, 30);

        jTextField16.setSize(new java.awt.Dimension(250, 40));
        jPanel7.add(jTextField16);
        jTextField16.setBounds(190, 20, 250, 40);

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel26.setText("उपप्रकार");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(30, 70, 150, 30);

        jTextField23.setSize(new java.awt.Dimension(250, 40));
        jPanel7.add(jTextField23);
        jTextField23.setBounds(190, 60, 250, 40);

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel27.setText("पाणी");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(30, 150, 120, 30);

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel28.setText("परिणाम");
        jPanel7.add(jLabel28);
        jLabel28.setBounds(30, 190, 120, 30);

        jTextField24.setSize(new java.awt.Dimension(250, 40));
        jPanel7.add(jTextField24);
        jTextField24.setBounds(190, 140, 250, 40);

        jTextField25.setSize(new java.awt.Dimension(250, 40));
        jPanel7.add(jTextField25);
        jTextField25.setBounds(190, 180, 250, 40);

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel29.setText("खर्चाची रक्कम");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(30, 110, 150, 30);

        jTextField26.setSize(new java.awt.Dimension(250, 40));
        jPanel7.add(jTextField26);
        jTextField26.setBounds(190, 100, 250, 40);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(20, 460, 470, 234);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("कामगार"));
        jPanel3.setAutoscrolls(true);
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel9.setText("कामाचा प्रकार");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 20, 150, 30);

        jTextField9.setSize(new java.awt.Dimension(250, 40));
        jPanel3.add(jTextField9);
        jTextField9.setBounds(190, 10, 250, 40);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel10.setText("कामगार संख्या");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(30, 60, 150, 30);

        jTextField10.setSize(new java.awt.Dimension(250, 40));
        jPanel3.add(jTextField10);
        jTextField10.setBounds(190, 50, 250, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(500, 350, 460, 110);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("पाणी व्यवस्थापन"));
        jPanel4.setAutoscrolls(true);
        jPanel4.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel13.setText("प्रकार");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(30, 30, 150, 30);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel15.setText("किती तास सोडले");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(30, 80, 150, 30);
        jPanel4.add(jTextField15);
        jTextField15.setBounds(190, 70, 200, 40);

        jComboBox3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "विहिरीचे पाणी", "बोरचे पाणी", "टँकर पाणी" }));
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(190, 30, 250, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(500, 220, 460, 130);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("खत व्यवस्थापन"));
        jPanel6.setAutoscrolls(true);
        jPanel6.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel21.setText("खत नाव");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(30, 30, 150, 30);
        jPanel6.add(jTextField14);
        jTextField14.setBounds(190, 20, 200, 40);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel22.setText("खत प्रमाण");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(30, 70, 150, 30);
        jPanel6.add(jTextField20);
        jTextField20.setBounds(190, 60, 200, 40);

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel23.setText("पाणी");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(30, 110, 120, 30);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel24.setText("परिणाम");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(30, 150, 120, 30);
        jPanel6.add(jTextField21);
        jTextField21.setBounds(190, 100, 200, 40);
        jPanel6.add(jTextField22);
        jTextField22.setBounds(190, 140, 200, 40);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(500, 20, 460, 200);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler fillerDown;
    private javax.swing.Box.Filler fillerLeft;
    private javax.swing.Box.Filler fillerRight;
    private javax.swing.Box.Filler fillerUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    
}
