/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.application.login;

import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import org.application.Application;
import org.application.dashboard.Dashboard;
import org.application.plot.PlotCreateUI;
import org.application.vevhar.VevharUI;
import org.application.plot.PlotSelectionTest;

/**
 *
 * @author abhayjadhav
 */
public class LoginInfo extends javax.swing.JPanel {

    /**
     * Creates new form LoginInfo
     */
    public LoginInfo() {
        initComponents();
        build_GUI();
    }
    
    public void build_GUI() {
        this.setPreferredSize(new Dimension(390, 270));//650, 435
        this.setBorder(BorderFactory.createTitledBorder(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("User Name :");
        add(jLabel1);
        jLabel1.setBounds(60, 70, 120, 20);
        add(textUserName);
        textUserName.setBounds(180, 70, 170, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Password   :");
        add(jLabel2);
        jLabel2.setBounds(60, 110, 120, 30);
        add(textPassword);
        textPassword.setBounds(180, 110, 170, 30);

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        add(buttonLogin);
        buttonLogin.setBounds(60, 170, 79, 29);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        add(buttonExit);
        buttonExit.setBounds(250, 170, 97, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Login sucessfull! ",
                    "Login", JOptionPane.INFORMATION_MESSAGE);
            this.removeAll();
            Application.getInstance().display_Panel(Dashboard.getInstance());
            setVisible(true);
            Application.getInstance().showMenu();
    }//GEN-LAST:event_buttonLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUserName;
    // End of variables declaration//GEN-END:variables
}
