/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.application;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.application.login.LoginInfo;

/**
 *
 * @author abhayjadhav
 */
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    private static Application instance = null;
    private static JPanel currentPanel = null;
    private double spaceV, spaceH;
    
    public static Application getInstance() {
        if (instance == null) {
            instance = new Application();
        }
        return instance;
    }
    
    public static JPanel getCurrentPanel() {
        return currentPanel;
    }
    
    public double getSpaceH() {
        return spaceH;
    }

    public void setSpaceH(double spaceH) {
        this.spaceH = spaceH;
    }

    public double getSpaceV() {
        return spaceV;
    }

    public void setSpaceV(double spaceV) {
        this.spaceV = spaceV;
    }
    
    public Application() {
        initComponents();
        build_gui();
    }
    
    private void build_gui() {
        jMenu1.setEnabled(false);
        jMenu2.setEnabled(false);
        LoginInfo loginInfo = new LoginInfo();
        currentPanel = loginInfo;
        this.add(loginInfo);
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension dimension = toolkit.getScreenSize();
        double width = dimension.getWidth() - 20;
        double height = dimension.getHeight() - 100;

        spaceH = (width - loginInfo.getPreferredSize().getWidth()) / 2;
        spaceV = (height - loginInfo.getPreferredSize().getHeight()) / 2;

//        this.addComponentListener(new WinResizeListener());
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        make_panel_Ceter(loginInfo);
//        hideShowMenu();
        this.setVisible(true);
    }
    
    public void showMenu() {
        jMenu1.setEnabled(true);
        jMenu2.setEnabled(true);
    }
    
    public void make_panel_Ceter(JPanel panel) {
        if (spaceH > 0 && spaceV > 0) {
            fillerLeft.setPreferredSize(new Dimension((int) spaceH, fillerLeft.getHeight()));
            fillerRight.setPreferredSize(new Dimension((int) spaceH, fillerLeft.getHeight()));
            fillerDown.setPreferredSize(new Dimension(fillerDown.getWidth(), (int) spaceV));
            fillerUp.setPreferredSize(new Dimension(fillerUp.getWidth(), (int) spaceV));
        }

    }
    
    public void display_Panel(JPanel panel) {
        if (currentPanel != null) {
            currentPanel.setVisible(false);
        }
        this.remove(currentPanel);
        this.revalidate();
        this.repaint();
        currentPanel = null;
        currentPanel = panel;
        this.add(currentPanel);
        Application.getInstance().setSpaceH((this.getWidth() - currentPanel.getPreferredSize().getWidth()) / 2);
        Application.getInstance().setSpaceV(((this.getHeight() - 60) - currentPanel.getPreferredSize().getHeight()) / 2);
        make_panel_Ceter(panel);
        panel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fillerLeft = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        fillerUp = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25));
        fillerRight = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0));
        fillerDown = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(fillerLeft, java.awt.BorderLayout.LINE_START);
        getContentPane().add(fillerUp, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(fillerRight, java.awt.BorderLayout.LINE_END);
        getContentPane().add(fillerDown, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("File");

        jMenuItem1.setText("Plot");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Application.getInstance();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler fillerDown;
    private javax.swing.Box.Filler fillerLeft;
    private javax.swing.Box.Filler fillerRight;
    private javax.swing.Box.Filler fillerUp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

}
